itemsA = {"蘋果", "香蕉", "鳳梨", "芭樂"}
itemsB = {"鳳梨", "蘋果", "水梨", "蓮霧"}
a1=input()
a2=input()
b1=input()
b2=input()
itemsA.add(a1)
itemsA.add(a2)
itemsA.remove("蘋果")
itemsB.add(b1)
itemsB.add(b2)
itemsB.remove("蓮霧")
lista=list(itemsA)
listb=list(itemsB)
lista.sort()
listb.sort()
print("iA:",lista)
print("iB:",listb)
union=list(itemsA.union(itemsB))
union.sort()
print("union:",union)
intersect=list(itemsA.intersection(itemsB))
intersect.sort()
print("intersection:",intersect)
AB=list(itemsA.difference(itemsB))
AB.sort()
print("A diff B:",AB)
BA=list(itemsB.difference(itemsA))
BA.sort()
print("B diff A:",BA)
C=itemsA.difference(itemsB)
D=itemsB.difference(itemsA)
xor=list(C)+list(D)
xor.sort()
print("A xor B:",xor)